# Generated by Django 5.1.6 on 2025-03-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_chatsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="Untitled Chat", max_length=255),
        ),
    ]
