# Generated by Django 5.1.6 on 2025-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0003_chatsession_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
