# Generated by Django 5.1.6 on 2025-04-16 22:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0004_chatsession_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
