// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sslzcxmqagzgicoerqck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzbHpjeG1xYWd6Z2ljb2VycWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMjUzOTAsImV4cCI6MjA1NDgwMTM5MH0._suJkA6pY2FMHPTzVkwj_fc9exiiw2UutQdQLPiEq2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);